##
## EPITECH PROJECT, 2019
## PSU_my_printf_2019
## File description:
## Makefile
##

LIBPATH = lib/my/

NAME = libmy.a

all : ${NAME}

${NAME} :
		make -C ${LIBPATH} all

clean :
		make -C ${LIBPATH} clean

fclean : clean
		rm ${NAME}

re : clean fclean all